version: "{build}"
image: "Visual Studio 2017"
build:
  verbosity: normal
skip_commits:
  files:
    - "*.md"
    - "LICENSE"
    - ".gitignore"

build_script:
  - ps: |
      C:\cygwin\bin\bash -l "/cygdrive/c/projects/xp-getentropy/appveyor-ci.sh" 2>&1 | %{ "$_" }
