name: GitHub CI

on:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Install meson and ninja
        run: |
          pip3 install meson ninja
      - name: Configure
        run: |
          meson setup -Dc_std=c11 b-release
      - name: Build and test
        working-directory: b-release
        run: |
          ninja -v
          .\t_basic
          .\t_more
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - macos-11.0
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add .local/bin to PATH
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - uses: actions/checkout@v2
      - name: Install meson and ninja
        run: |
          pip3 install setuptools
          pip3 install meson ninja
      - name: Configure
        run: |
          meson setup b-release
      - name: Build and test
        working-directory: ./b-release
        run: |
          ninja -v
          ./t_basic
          ./t_more
