name: GitHub CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
          - windows-2019
          - macos-11.0
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install meson
          pip install ninja
          meson setup b-release
          ninja -C b-release -v
          ./b-release/t_basic
          ./b-release/t_more
